package work.spacestime.file.service;

import java.util.List;

import work.spacestime.core.page.PageRequest;
import work.spacestime.core.page.PageResult;
import work.spacestime.file.model.SysFile;


public interface FileService {
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_File
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_File
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int insert(SysFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_File
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int insertSelective(SysFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_File
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    SysFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_File
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int updateByPrimaryKeySelective(SysFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_File
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int updateByPrimaryKeyWithBLOBs(SysFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_File
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int updateByPrimaryKey(SysFile record);
    
    
    /**
     * 分页查询
	 * 这里统一封装了分页请求和结果，避免直接引入具体框架的分页对象, 如MyBatis或JPA的分页对象
	 * 从而避免因为替换ORM框架而导致服务层、控制层的分页接口也需要变动的情况，替换ORM框架也不会
	 * 影响服务层以上的分页接口，起到了解耦的作用
	 * @param pageRequest 自定义，统一分页查询请求
	 * @return PageResult 自定义，统一分页查询结果
     */
	PageResult findPage(PageRequest pageRequest);
	
}
