kind: pipeline
type: docker
name: appTest

steps:
  - name: ssh commands
    image: appleboy/drone-ssh:1.5.7
    environment:
    settings:
      host:
        from_secret: ip
      username:
        from_secret: ssh_name
      password:
        from_secret: ssh_key
      port: 22
      script:
        - echo =======暂停容器=======
        - docker stop `docker ps -a | grep springdemo | awk '{print $1}' `
        - echo =======暂停旧容器和镜像=======
        - docker rm -f `docker ps -a | grep springdemo | awk '{print $1}' `
        - docker rmi `docker images | grep springdemo | awk '{print $3}' `
        - echo =======开始构建新镜像=======
        - cd /data/drone/helloDemo
        - docker build -t springdemo:v1 .
        - echo =======开始部署应用=======
        - docker run -d -p 8188:8180 --name springdemo springdemo:v1
        - echo =======清理构建文件=======
        # - rm -rf *
        - echo =======部署成功=======
        - echo =====TEST!======
        - echo "update file" >> a.txt
