package work.spacestime.product.service;

import work.spacestime.core.page.PageRequest;
import work.spacestime.core.page.PageResult;
import work.spacestime.product.model.SysProduct;


public interface ProductService {
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    SysProduct insert(SysProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int insertSelective(SysProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    SysProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int updateByPrimaryKeySelective(SysProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int updateByPrimaryKeyWithBLOBs(SysProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int updateByPrimaryKey(SysProduct record);
    
    
    /**
     * 分页查询
	 * 这里统一封装了分页请求和结果，避免直接引入具体框架的分页对象, 如MyBatis或JPA的分页对象
	 * 从而避免因为替换ORM框架而导致服务层、控制层的分页接口也需要变动的情况，替换ORM框架也不会
	 * 影响服务层以上的分页接口，起到了解耦的作用
	 * @param pageRequest 自定义，统一分页查询请求
	 * @return PageResult 自定义，统一分页查询结果
     */
	PageResult findPage(PageRequest pageRequest);

}
