package work.spacestime.product.model;

import java.io.Serializable;
import java.util.Date;

public class SysProduct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.id
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    private Long id;
    
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.name
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.create_by
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.create_time
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.last_update_by
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.last_update_time
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.del_flag
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    private Byte delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.descr
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    private String descr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.detail
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.imgs
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    private String imgs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.moves
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    private String moves;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_product.mark
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_product
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.id
     *
     * @return the value of sys_product.id
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.id
     *
     * @param id the value for sys_product.id
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.name
     *
     * @return the value of sys_product.name
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.name
     *
     * @param name the value for sys_product.name
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.create_by
     *
     * @return the value of sys_product.create_by
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.create_by
     *
     * @param createBy the value for sys_product.create_by
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.create_time
     *
     * @return the value of sys_product.create_time
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.create_time
     *
     * @param createTime the value for sys_product.create_time
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.last_update_by
     *
     * @return the value of sys_product.last_update_by
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.last_update_by
     *
     * @param lastUpdateBy the value for sys_product.last_update_by
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.last_update_time
     *
     * @return the value of sys_product.last_update_time
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.last_update_time
     *
     * @param lastUpdateTime the value for sys_product.last_update_time
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.del_flag
     *
     * @return the value of sys_product.del_flag
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.del_flag
     *
     * @param delFlag the value for sys_product.del_flag
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.descr
     *
     * @return the value of sys_product.descr
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.descr
     *
     * @param descr the value for sys_product.descr
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.detail
     *
     * @return the value of sys_product.detail
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.detail
     *
     * @param detail the value for sys_product.detail
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.imgs
     *
     * @return the value of sys_product.imgs
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public String getImgs() {
        return imgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.imgs
     *
     * @param imgs the value for sys_product.imgs
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public void setImgs(String imgs) {
        this.imgs = imgs == null ? null : imgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.moves
     *
     * @return the value of sys_product.moves
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public String getMoves() {
        return moves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.moves
     *
     * @param moves the value for sys_product.moves
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public void setMoves(String moves) {
        this.moves = moves == null ? null : moves.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_product.mark
     *
     * @return the value of sys_product.mark
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_product.mark
     *
     * @param mark the value for sys_product.mark
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateBy=").append(lastUpdateBy);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", descr=").append(descr);
        sb.append(", detail=").append(detail);
        sb.append(", imgs=").append(imgs);
        sb.append(", moves=").append(moves);
        sb.append(", mark=").append(mark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysProduct other = (SysProduct) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getLastUpdateBy() == null ? other.getLastUpdateBy() == null : this.getLastUpdateBy().equals(other.getLastUpdateBy()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()))
            && (this.getDescr() == null ? other.getDescr() == null : this.getDescr().equals(other.getDescr()))
            && (this.getDetail() == null ? other.getDetail() == null : this.getDetail().equals(other.getDetail()))
            && (this.getImgs() == null ? other.getImgs() == null : this.getImgs().equals(other.getImgs()))
            && (this.getMoves() == null ? other.getMoves() == null : this.getMoves().equals(other.getMoves()))
            && (this.getMark() == null ? other.getMark() == null : this.getMark().equals(other.getMark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getLastUpdateBy() == null) ? 0 : getLastUpdateBy().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        result = prime * result + ((getDescr() == null) ? 0 : getDescr().hashCode());
        result = prime * result + ((getDetail() == null) ? 0 : getDetail().hashCode());
        result = prime * result + ((getImgs() == null) ? 0 : getImgs().hashCode());
        result = prime * result + ((getMoves() == null) ? 0 : getMoves().hashCode());
        result = prime * result + ((getMark() == null) ? 0 : getMark().hashCode());
        return result;
    }

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
}