package work.spacestime.product.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import work.spacestime.product.model.SysProduct;

@Mapper
public interface SysProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int insert(SysProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int insertSelective(SysProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    SysProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int updateByPrimaryKeySelective(SysProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int updateByPrimaryKeyWithBLOBs(SysProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int updateByPrimaryKey(SysProduct record);
    
    List<SysProduct> findPage();
    
    List<SysProduct> findPageByName(String name);
    
}