package work.spacestime.file.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import work.spacestime.file.model.SysFile;

@Mapper
public interface SysFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_File
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_File
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int insert(SysFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_File
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int insertSelective(SysFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_File
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    SysFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_File
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int updateByPrimaryKeySelective(SysFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_File
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int updateByPrimaryKeyWithBLOBs(SysFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_File
     *
     * @mbg.generated Fri Sep 30 03:39:22 UTC 2022
     */
    int updateByPrimaryKey(SysFile record);
    
    List<SysFile> findPage();
    
    List<SysFile> findPageByName(String name);
}