package work.spacestime.file.model;

import java.io.Serializable;
import java.util.Date;

public class SysFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.id
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.type
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.file_path
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.url
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.link_id
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    private Long linkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.del_flag
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    private Byte delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.create_by
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.create_time
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.last_update_by
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.last_update_time
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_file
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.id
     *
     * @return the value of sys_file.id
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.id
     *
     * @param id the value for sys_file.id
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.type
     *
     * @return the value of sys_file.type
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.type
     *
     * @param type the value for sys_file.type
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.file_path
     *
     * @return the value of sys_file.file_path
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.file_path
     *
     * @param filePath the value for sys_file.file_path
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.url
     *
     * @return the value of sys_file.url
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.url
     *
     * @param url the value for sys_file.url
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.link_id
     *
     * @return the value of sys_file.link_id
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public Long getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.link_id
     *
     * @param linkId the value for sys_file.link_id
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public void setLinkId(Long linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.del_flag
     *
     * @return the value of sys_file.del_flag
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.del_flag
     *
     * @param delFlag the value for sys_file.del_flag
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.create_by
     *
     * @return the value of sys_file.create_by
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.create_by
     *
     * @param createBy the value for sys_file.create_by
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.create_time
     *
     * @return the value of sys_file.create_time
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.create_time
     *
     * @param createTime the value for sys_file.create_time
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.last_update_by
     *
     * @return the value of sys_file.last_update_by
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.last_update_by
     *
     * @param lastUpdateBy the value for sys_file.last_update_by
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.last_update_time
     *
     * @return the value of sys_file.last_update_time
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.last_update_time
     *
     * @param lastUpdateTime the value for sys_file.last_update_time
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", filePath=").append(filePath);
        sb.append(", url=").append(url);
        sb.append(", linkId=").append(linkId);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateBy=").append(lastUpdateBy);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysFile other = (SysFile) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getFilePath() == null ? other.getFilePath() == null : this.getFilePath().equals(other.getFilePath()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getLinkId() == null ? other.getLinkId() == null : this.getLinkId().equals(other.getLinkId()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getLastUpdateBy() == null ? other.getLastUpdateBy() == null : this.getLastUpdateBy().equals(other.getLastUpdateBy()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file
     *
     * @mbg.generated Tue Oct 04 07:15:48 UTC 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getFilePath() == null) ? 0 : getFilePath().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getLinkId() == null) ? 0 : getLinkId().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getLastUpdateBy() == null) ? 0 : getLastUpdateBy().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        return result;
    }
}